#!/bin/bash
#
# This script launch a Jenkins swarm[1] plugin client which automatically
# registers this container as a Jenkins slave.

source /opt/app-src/jenkins/common.sh

# TODO: This should be constructed from an environment variables
JENKINS_MASTER_URL=${JENKINS_MASTER_URL:-http://jenkins:8080}

# The swarm client has to match with the plugin installed in Jenkins master.
# Download latest version from:
# http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/plugins/swarm-client/2.0/
SWARM_CLIENT_JAR="${JENKINS_HOME}/swarm-client-2.0-jar-with-dependencies.jar"

# NOTE: You have to provide the Jenkins password by passing '-password <pass>'
# parameter
# Remove last two arguments which are ID's kubernetes-plugin use, but we don't
# want.
slave_name="${@: -1}"

set -- "${@:1:$(($#-2))}"
exec java -jar ${SWARM_CLIENT_JAR} \
  -master "${JENKINS_MASTER_URL}" \
  -mode exclusive \
  -name ${slave_name} \
  -fsroot "${JENKINS_HOME}" \
  -username ${JENKINS_USERNAME:-admin} \
  -executors 1 \
  -disableSslVerification "$@"
